# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               MyOdoo.cc
tagline:             'Odoo Implementation Log'
description:         'Odoo實施經驗分享'
url:                 http://www.myodoo.cc
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
paginate_path: 		 "page:num"

# About/contact
author:
  name:              Paul Lu
  url:               http://blog.retailscm.com
  email:             luss613@gmail.com

# Custom vars
version:             1.0.0
