# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Odoo.live
tagline:             'Odoo Implementation Log'
description:         'Odoo实施经验分享'
url:                 http://www.odoo.live
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
paginate_path: 		 "page:num"

# About/contact
author:
  name:              Paul Lu
  url:               http://blog.retailscm.com
  email:             luss613@gmail.com

# Custom vars
version:             1.0.0
